<template>
  <section class="max-w-7xl mx-auto px-4 py-10 space-y-10">
    <h1 class="text-3xl font-bold">memverse Demo</h1>

    <el-card>
      <template #header>
        <div class="flex items-center justify-between">
          <span class="font-semibold">Multimodal: Image → Mock Caption</span>
        </div>
      </template>
      <div class="grid md:grid-cols-2 gap-6">
        <UploadImage @analyze="analyzeImage" />
        <div>
          <h3 class="font-semibold mb-2">Result</h3>
          <div v-if="imageCaption" class="rounded-lg border p-3 bg-gray-50 text-gray-700">
            {{ imageCaption }}
          </div>
          <div v-else class="text-gray-400">Upload an image to generate a mock caption.</div>
          <div class="mt-4 text-sm text-gray-500">
            This simulates a vision model output. Integrate your backend vision API here.
          </div>
        </div>
      </div>
    </el-card>

    <el-card>
      <template #header>
        <div class="flex items-center justify-between">
          <span class="font-semibold">Memory: Short vs Long Term</span>
        </div>
      </template>
      <div class="grid md:grid-cols-3 gap-6">
        <div class="md:col-span-1 space-y-3">
          <el-input v-model="shortInput" placeholder="Short-term note..." />
          <BaseButton type="primary" @click="addShortNote">Add Short</BaseButton>
          <BaseButton @click="clearShortMem">Clear Short</BaseButton>
          <div class="text-xs text-gray-500">Short-term lives in session only.</div>
        </div>
        <div class="md:col-span-1 space-y-3">
          <el-input v-model="longInput" placeholder="Long-term note..." />
          <BaseButton type="primary" @click="addLongNote">Add Long</BaseButton>
          <BaseButton @click="clearLongMem">Clear Long</BaseButton>
          <div class="text-xs text-gray-500">Long-term persists in localStorage.</div>
        </div>
        <div class="md:col-span-1">
          <h3 class="font-semibold mb-2">All Memories</h3>
          <ul class="space-y-2 max-h-60 overflow-auto">
            <li v-for="m in allMemories" :key="m.id" class="rounded border p-2 flex items-start justify-between gap-3">
              <div>
                <span class="text-xs px-2 py-0.5 rounded bg-brand-50 text-brand-600 mr-2">{{ m.type }}</span>
                <span class="text-gray-800">{{ m.content }}</span>
                <div class="text-xs text-gray-400">{{ new Date(m.createdAt).toLocaleString() }}</div>
              </div>
              <BaseButton size="small" @click="remove(m.id)">Remove</BaseButton>
            </li>
          </ul>
        </div>
      </div>
    </el-card>

    <el-card>
      <template #header>
        <div class="flex items-center justify-between">
          <span class="font-semibold">Parametric Memory (Model Knowledge) - Mock</span>
        </div>
      </template>
      <div class="grid md:grid-cols-2 gap-6">
        <div class="space-y-3">
          <el-input
            v-model="q"
            placeholder="Ask about general knowledge (e.g., 'What is Vue 3?')"
            @keyup.enter.native="ask"
          />
          <BaseButton type="primary" @click="ask">Ask</BaseButton>
        </div>
        <div class="rounded-lg border p-3 bg-gray-50 text-gray-700 min-h-[6rem]">
          <div v-if="a">{{ a }}</div>
          <div v-else class="text-gray-400">Ask a question to see a mocked parametric response.</div>
        </div>
      </div>
      <div class="mt-3 text-sm text-gray-500">
        In production, parametric memory refers to knowledge encoded in the model weights. Here we simulate responses
        without calling a real model.
      </div>
    </el-card>
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import UploadImage from '@/components/base/UploadImage.vue'
import BaseButton from '@/components/base/BaseButton.vue'
import { useMemoryStore } from '@/stores/memory'
import { useNotification } from '@/composables/useNotification'

const { success } = useNotification()

// Multimodal (mock)
const imageCaption = ref<string>('')
async function analyzeImage(file: File) {
  // Mock: create a simple caption using file name
  const name = file.name.replace(/\.[^.]+$/, '')
  imageCaption.value = `Image "${name}": a high-level mock caption generated by memverse.`
  success('Image analyzed (mock).')
}

// Memory store
const memory = useMemoryStore()
const shortInput = ref<string>('')
const longInput = ref<string>('')

function addShortNote() {
  if (!shortInput.value.trim()) return
  memory.addShort(shortInput.value.trim())
  shortInput.value = ''
  success('Added short-term memory.')
}

function addLongNote() {
  if (!longInput.value.trim()) return
  memory.addLong(longInput.value.trim())
  longInput.value = ''
  success('Added long-term memory.')
}

function clearShortMem() {
  memory.clearShort()
  success('Cleared short-term memories.')
}

function clearLongMem() {
  memory.clearLong()
  success('Cleared long-term memories.')
}

const allMemories = memory.allMemories
const remove = memory.remove

// Parametric (mock Q&A)
const q = ref<string>('')
const a = ref<string>('')
function ask() {
  const text = q.value.trim().toLowerCase()
  if (!text) return
  if (text.includes('vue')) {
    a.value = 'Vue 3 is a progressive framework for building user interfaces using a reactive component model.'
  } else if (text.includes('pinia')) {
    a.value = 'Pinia is the officially recommended state management library for Vue, lightweight and modular.'
  } else {
    a.value = 'This is a mocked parametric response. Connect your LLM to answer from encoded knowledge.'
  }
}
</script>


